### PR TITLE
minor linting and fixups

### PR DESCRIPTION
**Pull request by siriobalmelli**
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>

### CODE REVIEW

**Comment by siriobalmelli** [comment]
Hello :)

I am getting familiar with this codebase for possible use, and while reading through found some minor corrections:

- commit 760ebce removes some trailing spaces found in the source files
- commit 119870b adds an `.lvimrc` file so that any Vim user (like) me is normalized to the code style you have set for this project
- commit 2197f18 fixes some typographical errors found in the source

**Comment by MaJerle** [comment]
Anything functional that it problematic?

**Comment by siriobalmelli** [comment]
No, this is not functionally breaking or high priority.

If the experience of sending pull requests to this project is positive, I will probably contribute more in the future ;)

**Comment by MaJerle** [comment]
Certainly, if it complies with everything I have on problem to merge.

**Pull request merged**
